apiVersion: apps/v1
kind: Deployment
metadata:
  name: multiply
spec:
  replicas: 3
  selector:
    matchLabels:
      app: multiply
  template:
    metadata:
      labels:
        app: multiply
    spec:
      containers:
        - name: multiply
          image: ghcr.io/maxanderson95/calculator-microservice/multiply:latest
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "80"
          ports:
            - containerPort: 80
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - multiply
                topologyKey: "kubernetes.io/hostname"
