services:
  frontend:
    build:
      context: ./services/frontend
    container_name: frontend
    environment:
      - PORT=80
      - ADD_SERVICE_URL=http://add
      - SUBTRACT_SERVICE_URL=http://subtract
      - MULTIPLY_SERVICE_URL=http://multiply
      - DIVIDE_SERVICE_URL=http://divide
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8000:80"
    restart: "no"

  add:
    build:
      context: ./services/add
    container_name: add
    environment:
      - PORT=80
    restart: "no"

  subtract:
    build:
      context: ./services/subtract
    container_name: subtract
    environment:
      - PORT=80
      - ADD_SERVICE_URL=http://add
    restart: "no"

  multiply:
    build:
      context: ./services/multiply
    container_name: multiply
    environment:
      - PORT=80
    restart: "no"

  divide:
    build:
      context: ./services/divide
    container_name: divide
    environment:
      - PORT=80
    restart: "no"

  redis:
    image: redis
    container_name: redis
    restart: "no"
    command: /bin/bash -c 'rm -rf /data/* && redis-server'
