services:
  frontend:
    build:
      context: ./services/frontend
    container_name: frontend
    environment:
      - PORT=80
      - ADD_SERVICE_URL=http://add
      - SUBTRACT_SERVICE_URL=http://subtract
      - MULTIPLY_SERVICE_URL=http://multiply
      - DIVIDE_SERVICE_URL=http://divide
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - OTEL_SERVICE_NAME=frontend
      - OTEL_TRACES_EXPORTER=console,otlp
      - OTEL_METRICS_EXPORTER=console
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://jager:4317
    ports:
      - "8000:80"
    restart: "no"
    depends_on:
      - add
      - subtract
      - multiply
      - divide
      - redis
      - postgres

  add:
    build:
      context: ./services/add
    container_name: add
    environment:
      - PORT=80
      - OTEL_SERVICE_NAME=add
      - OTEL_TRACES_EXPORTER=console,otlp
      - OTEL_METRICS_EXPORTER=console
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://jager:4317
    restart: "no"
    ports:
      - "8001:80"

  subtract:
    build:
      context: ./services/subtract
    container_name: subtract
    environment:
      - PORT=80
      - ADD_SERVICE_URL=http://add
      - OTEL_SERVICE_NAME=subtract
      - OTEL_TRACES_EXPORTER=console,otlp
      - OTEL_METRICS_EXPORTER=console
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://jager:4317
    restart: "no"
    depends_on:
      - add
    ports:
      - "8002:80"

  multiply:
    build:
      context: ./services/multiply
    container_name: multiply
    environment:
      - PORT=80
      - OTEL_SERVICE_NAME=multiply
      - OTEL_TRACES_EXPORTER=console,otlp
      - OTEL_METRICS_EXPORTER=console
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://jager:4317
    restart: "no"
    ports:
      - "8003:80"

  divide:
    build:
      context: ./services/divide
    container_name: divide
    environment:
      - PORT=80
      - OTEL_SERVICE_NAME=divide
      - OTEL_TRACES_EXPORTER=console,otlp
      - OTEL_METRICS_EXPORTER=console
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://jager:4317

    restart: "no"
    ports:
      - "8004:80"

  redis:
    image: redis
    container_name: redis
    restart: "no"
    command: /bin/bash -c 'rm -rf /data/* && redis-server'
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    container_name: postgres
    restart: "no"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  jager:
    image: jaegertracing/all-in-one
    container_name: jager
    restart: "no"
    ports:
      - "16686:16686"

  pgweb:
    image: sosedoff/pgweb
    container_name: pgweb
    restart: "no"
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      - PGWEB_DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable

  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    container_name: redis-commander
    restart: "no"
    ports:
      - "8082:8081"
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=local:redis:6379
