apiVersion: apps/v1
kind: Deployment
metadata:
  name: subtract
spec:
  selector:
    matchLabels:
      app: subtract
  template:
    metadata:
      labels:
        app: subtract
    spec:
      containers:
        - name: subtract
          image: ghcr.io/maxanderson95/calculator-microservice/subtract:latest
          env:
            - name: PORT
              value: "80"
            - name: ADD_SERVICE_HOST
              value: "http://add-service"
          ports:
            - containerPort: 80
